/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      fontSize: {
        'ios-large-title': ['2.125rem', { lineHeight: '2.5rem', fontWeight: '700', letterSpacing: '-0.02em' }],
        'ios-title-1': ['1.75rem', { lineHeight: '2.125rem', fontWeight: '700', letterSpacing: '-0.02em' }],
        'ios-title-2': ['1.375rem', { lineHeight: '1.75rem', fontWeight: '700', letterSpacing: '-0.01em' }],
        'ios-title-3': ['1.25rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'ios-headline': ['1.0625rem', { lineHeight: '1.375rem', fontWeight: '600' }],
        'ios-body': ['1.0625rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'ios-callout': ['1rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'ios-subhead': ['0.9375rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'ios-footnote': ['0.8125rem', { lineHeight: '1.125rem', fontWeight: '400' }],
        'ios-caption': ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
      },
      borderRadius: {
        ios: '0.625rem',
        'ios-md': '0.75rem',
        'ios-lg': '0.875rem',
        'ios-xl': '1.25rem',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        'tab-bar': 'var(--tab-bar-height)',
        'safe-top': 'var(--app-sat, env(safe-area-inset-top, 0px))',
        'safe-bottom': 'var(--safe-bottom)',
      },
      colors: {
        border: 'hsl(var(--border))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        brand: {
          gold: '#d0ab63',
          maroon: '#8f2126',
          'maroon-dark': '#59191f',
          'maroon-darker': '#41151d',
          'maroon-deep': '#331518',
          'maroon-black': '#160f10',
          'maroon-charcoal': '#1f1414',
          'maroon-rust': '#3f181c',
        },
        primary: {
          DEFAULT: '#d0ab63',
          foreground: '#160f10',
          50: '#fdf8ed',
          100: '#f9ecd4',
          200: '#f2d9a8',
          300: '#e9c078',
          400: '#d0ab63',
          500: '#b89247',
          600: '#9a7639',
          700: '#7a5c30',
          800: '#654c2c',
          900: '#554028',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive-hsl))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        tint: 'var(--tint)',
        'ios-destructive': 'var(--destructive)',
      },
      boxShadow: {
        'ios-card': '0 4px 24px -4px rgba(0, 0, 0, 0.35)',
        'tab-bar': '0 -1px 0 rgba(255, 255, 255, 0.08)',
      },
      backdropBlur: {
        ios: '20px',
      },
    },
  },
  plugins: [],
};
